language: python
python:
  - "3.6"
  - "3.7"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install pytest==4.5.0
  - pip install codecov==2.0.15
  - pip install pytest-cov==2.7.1
script:
  - pytest --cov-report term --cov=investpy tests/